language: python
python:
  - '3.5'
  - '3.6'
  - nightly
matrix:
  include:
  - python: 3.7
    dist: xenial
sudo: true
before_install:
  - pip install coverage coveralls pytest-cov
install:
  - pip install .
script:
  - py.test --cov=sentence_splitter tests/
after_success:
  - coveralls
